### ISSUE TITLE
Is it possible to add parser to parse mint type of pumpfun and swap type of raydium?

### ISSUE THREAD

**Issue by liuqiandev** [0xjeffro/tx-parser#4]
pumpfun mint and buy  signature

`2s393PSYYxJJJfGiwHf18HZeC68nZs44ssbeB4aAkeYMyd1dyiiu3yVmGyRWZuArk5HzYDgVxYfhKLYd2CJ8kCBj`

raydim swap signature

`3aQZsNRUbNXpH54GQEaxFpWZsmL554cYGGtWqqoypz8b6LUDYprbRd9AwgivXRLtFBYCU6MU6e9ANurwP8dCMV6`

**Comment by 0xjeffro** [comment]
Got it! I’ll add those parsers soon, should be done by tomorrow.

**Comment by 0xjeffro** [comment]
> 中国人？是的话就没必要用英文交流了

嗯嗯，但我目前在UTC-7时区，等明天白天我来处理这个问题哈。
